// auth/AuthContext.jsx — ALREADY BUILT for you (from the AuthContext lesson).
// You read the current user with useAuth().user in your gates. Do NOT edit this file.
import { createContext, useContext, useReducer } from "react";

// Private to this file — components read through useAuth(), never the raw context.
const AuthContext = createContext(null);

const initialState = { user: null, accessToken: null };

function authReducer(state, action) {
  switch (action.type) {
    case "LOGIN":
      return { user: action.payload.user, accessToken: action.payload.accessToken };
    case "LOGOUT":
      return { user: null, accessToken: null };
    case "TOKEN_REFRESHED":
      return { ...state, accessToken: action.payload.accessToken };
    default:
      return state;
  }
}

export function AuthProvider({ children }) {
  const [state, dispatch] = useReducer(authReducer, initialState);
  return (
    <AuthContext.Provider value={{ ...state, dispatch }}>
      {children}
    </AuthContext.Provider>
  );
}

export function useAuth() {
  const context = useContext(AuthContext);
  if (context === null) {
    throw new Error("useAuth must be used within an AuthProvider");
  }
  return context;
}
